### ISSUE TITLE
Suggestion for History

### ISSUE THREAD

**Issue by mikhoul** [brandon1024/find#199]
It would be useful also it "Find" had the ability to keep a search history for the search terms/query.

Regards :octocat:

**Comment by mghoffmann** [comment]
This would be really great. This is an awesome tool that I use a lot, but I have to keep a text file with all my frequently-used expressions. It's a pain to have to type `\$[0-9][0-9][0-9]\.?([0-9][0-9])?` to search for price changes, for example. If I could save an expression called "3-digit price" and load it quickly with this extension that would be great. Maybe even assign a custom keyboard shortcut for that specific search expression?

**Comment by MartinLichtblau** [comment]
You can do that already by using the omnibar, since it saves all inputs in your browser-history. 
1. You can either write just the regex; then you have to remember parts of search string. E.g. `[“"](.*?)["”]`

2. Or you include an additional title in the search for easier recall; but then you have to delete this part before pressing enter. E.g. `[“"](.*?)["”] quotes` Since the cursor>caret is at the end, you just have to click once (Ctrl+Backspace) to delete the title.

**Comment by brandon1024** [comment]
Thank you all for your patience!

Here is the initial version of the the history pane.
![image](https://user-images.githubusercontent.com/22732449/52184968-631d2700-27f0-11e9-9a61-da60f2d3d129.png)

Expect this feature to be released soon.
