### ISSUE TITLE
No highlighting on pre-install tabs

### ISSUE THREAD

**Issue by pacohojaverde** [brandon1024/find#211]
After I installed the Firefox add-on, I tried to use it on some of my already opened tabs, but even though the find box showed how many matches there were, no highlighting was present. It was only after reloading that tab or opening a new one that the highlight functionality was visible.

It must have something to do with the first time installation. The image below is an example of a search I tried to perform on a SoundCloud tab that I had open before the extension was added:

![SoundCloud Highlighting Problem](https://user-images.githubusercontent.com/2936762/45371939-98ef1400-b5a0-11e8-82d9-f81f9f028c5f.PNG)

**Comment by brandon1024** [comment]
Strange issue. The extension is designed to automatically inject content scripts into existing pages on install, and this feature works in Chrome. I will investigate this further.

**Comment by brandon1024** [comment]
I think I found the issue here. browser.tabs.executeScript(...) will throw an error if the script cannot be injected into the page due to insufficient permissions. In Chrome, this is handled in `backend.js` by checking the url, and skipping chrome settings pages. However, this was not implemented for Firefox.

Simple fix!
