### ISSUE TITLE
Make search field larger (or even multiline)

### ISSUE THREAD

**Issue by WoLpH** [brandon1024/find#217]
## Issue Description

The big advantage of this extension is obviously being able to use regular expressions. The downside of regular expressions is that they tend to get long quite easily so it would be nice if the search field would be a bit larger.

Perhaps even having multiple lines (which collapse to a single line when actually searching).

## Screenshots and Documentation

![image](https://user-images.githubusercontent.com/270571/47572892-58730c00-d93c-11e8-8e59-c927606ecffa.png)

**Comment by brandon1024** [comment]
The reason the extension popup is small is because I wanted to keep it as similar as possible to the native tool. 

However, you're right, it could be larger. When the settings button was added, the size of the popup wasn't adjusted appropriately. Also, I noticed that the width of the index text is shorter on the native tool as well.

**Comment by WoLpH** [comment]
I understand the reasoning and I kind of agree with it.
However, it's also a power user tool and we like to abuse features ;)
