### ISSUE TITLE
Keep find+ window from closing automatically

### ISSUE THREAD

**Issue by Apex50** [brandon1024/find#235]
## Issue Description
A very useful feature of find+ is the ability to jump to the next occurrence of what you are searching for.
However, clicking anywhere in the searched page or selecting something - or even changing focus to another window - causes the find+ window to close. Upon reopening, the occurrence number of the search terms is reset. Therefore, one cannot jump to a particular occurrence, click something there, and then move on the next occurrence.

## Steps to Reproduce
- Jump to any occurrence (except the first one)
- Click anywhere on the page (this causes the find+ window to close)
- Reopen the find+ window
- The occurrence number is reset

## Tasks
- Keep the find+ window open - unless the X button is clicked - such that the occurrence number does not reset, even when clicking/selecting something in the window (most preferred)
- Or keep track of occurrence, even after find+ window disappears
- Or add the ability to skip to a given (entered) occurrence (least preferred)

**Comment by brandon1024** [comment]
Hello @Apex50, thanks for using my extension!

This is a known issue, and I discuss about it [here](https://github.com/brandon1024/find/wiki/FAQ-:-General#q-the-extension-keeps-closing-whenever-i-use-the-page-scrollbars-or-click-anything-on-the-page).

I'm working on a feature that would circumvent this issue by placing the extension popup as a iframe in the page. However this issue is on the backburner for now (school takes precedence sadly). Here's the [issue](https://github.com/brandon1024/find/issues/198), you can follow the progress there.
