### ISSUE TITLE
Feature Request: support diacritical words

### ISSUE THREAD

**Issue by YandLiu** [brandon1024/find#262]
For example, I want to find "café" by typing "cafe".

**Comment by brandon1024** [comment]
Hello @YandLiu , thank you for your interest!

This issue is a bit tricky. At the moment, the extension only supports basic characters because it uses a custom HTML character entity decoder which only supports ASCII (plus a few other) characters.

There's an issue open #252 that would fix this issue. However, I've decided that I won't go this route because the library would slow down the extension by a considerable factor.

So instead, I might consider updating the character entity decoder to support unicode Plane 0 characters, which includes diacritical characters.
