### ISSUE TITLE
Search for AJAX content

### ISSUE THREAD

**Issue by kajman-cz** [brandon1024/find#300]
When I search for a regexp, and after the content is loaded by AJAX (or changed), the search result will not be highlighted in that new content.

Maybe you could use MutationObserver for new DOM parts.
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by brandon1024** [comment]
I've been thinking about how this could work over the past year, but I've decided that I'm not going to implement this functionality for a few reasons.

Right now, find+ injects elements in the page so that parsing and highlighting can work. If I were to use a mutation observer on the page, it could be triggered by find+ itself. Further, some pages are heavily dynamic and parsing the page every time new content is loaded could be dramatically slow (find+ struggles with large pages as it is, and it's already as efficient as I was able to get it).

Find+ was built for for developers to use in static content like CI debug output, source code and reference manuals. It's not really designed to be used in sites with dynamic content.

I'm sorry to bear the bad news, but you're more than welcome to fork the repository and make any adjustments you wish!
