### ISSUE TITLE
Document Firefox shortcut

### ISSUE THREAD

**Issue by camsteffen** [brandon1024/find#322]
Is there a way to open find+ in Firefox with a keyboard shortcut? The help page shows instructions for Chrome.

**Comment by VariableReferee** [comment]
Hey camsteffen, I use ctrl-shift-f and the search box pops open in Firefox for me.

**Comment by camsteffen** [comment]
Indeed, thanks!

**Comment by mfn** [comment]
Ah that information!

It would be great if that could be mentioned in the hover label 😄 
![image](https://user-images.githubusercontent.com/87493/90022008-4188df80-dcb2-11ea-8cf9-62a0556d2746.png)

**Comment by VariableReferee** [comment]
That's a great idea. I second that!

**Comment by brandon1024** [comment]
@mfn I can't put the keyboard shortcut info there, because that text comes from the extension name in the manifest file. That information is [used in a bunch of places](https://developer.chrome.com/extensions/manifest/name#name) (install dialog and the web store), and might be used by the Mozilla add-on store too.

The project documentation hasn't been refreshed in a while, so I'm going to update the docs to make the extension shortcut a bit more obvious!

**Comment by brandon1024** [comment]
Project README was updated, hopefully this helps :-) Closing this issue.
