### ISSUE TITLE
Having uBlock origin enabled on Facebook make this not work

### ISSUE THREAD

**Issue by SelaO** [brandon1024/find#334]
## Steps to Reproduce
install and enable uBlock origin extension
search for anything on facebook
nothing will come up, but if I disable uBlock, then the search works

**Comment by brandon1024** [comment]
@SelaO does this occur on pages other than Facebook?

**Comment by SelaO** [comment]
@brandon1024 Not that I noticed

**Comment by brandon1024** [comment]
What is your use case for using this extension on Facebook? This extension was built primarily for searching through pages of structured text, like CI pipeline log output or documentation.

My guess is that uBlock is injecting markup into the page and messing with the extension's markup. This extension isn't resilient to dynamic content or externally injected content, simply because this extension wasn't designed to handle such cases.

**Comment by brandon1024** [comment]
Closing this for now.
