### ISSUE TITLE
Reduce required permissions

### ISSUE THREAD

**Issue by fm-sys** [brandon1024/find#338]
## Issue Description
The add-on requires the permission "Access your data for all websites" which AFAIK also allows reading stored passwords while other extensions show, that it's possible to do the same thing without any permissions. 

See https://addons.mozilla.org/de/firefox/addon/multiple-highlight/ as an example...

**Comment by brandon1024** [comment]
@raspatan  Hold on, woah. No need to be so aggressive. Please, let's be respectful.

Chrome has some alarmist messaging around the permissions that the extension needs. Really all it's asking for is that javascript be loaded into every page. Don't be alarmed. This extension never talks to any servers and does absolutely nothing with your data. You're welcome to read through the source code.

Here are all the [persmissions the extension needs](https://github.com/brandon1024/find/blob/develop/manifest.json), and explanations with each:

## "tabs",
Pretty much every extension ever needs this one. This allows the extension to interact with tabs you have open.

## "activeTab",
Same thing here. This is used to query for the tab that is currently active.

## "background",
A background script is needed to act as a mediator between the UI (popup) and content scripts running in the page. This background script is only activated when you actually start up the extension popup. The background script also does a bit work, specifically around building an occurrence map from text in the page against a regular expression. This is created to help speedup the extension, for quicker lookup. Read through the source [here](https://github.com/brandon1024/find/blob/develop/background/background.js).

## "storage",
Some features require local storage, like settings and history features. You can find the relevant source [here](https://github.com/brandon1024/find/blob/develop/popup/js/storage.js).

##  "clipboardWrite",
Find+ has a feature that can copy one (or all) occurrences of a regex to the clipboard. To do that, the extension needs this permission.

## "contextMenus",
This allows the extension to create a "Show Help" context menu when you right click on the popup icon, so that you can go right to the find+ documentation.

## "<all_urls>"
This allows the extension to work on all pages. Otherwise, it would be an opt in model, where I'd have to define a huge list of URLs where this extension would work.

@fm-sys Does this help explain your issue?

**Comment by brandon1024** [comment]
@fm-sys yeah, my hands are pretty tied here. I could remove some permissions, but that would mean taking away features. I'd get crucified by the community if I did that..

Do you mind if I close this ticket?
