### ISSUE TITLE
Display Info Message In chrome:// and Web Store

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#96]
To prevent malicious Chrome extensions from installing other extensions and changing user settings, developers disabled chrome extensions from injecting Javascript into any webpage with the url `chrome://` or `https://chrome.google.com/webstore/category/extensions`. As a result, our extension appears to be unresponsive on these web pages, and this could confuse users who are not familiar with this extension limitation.

It would be beneficial to display a small message to notify users of this.

**Comment by surlyhacker** [comment]
This is broken now since Chrome Web Store URLs start with https://chromewebstore.google.com/
But the code is looking for `url.match(/https:\/\/chrome\.google\.com\/webstore\/.*/)`
https://github.com/brandon1024/find/blob/79e3acb7cc0bba62d45c0cbb9ba9cafc5a208da5/popup/js/browser-action.js#L271

So the extension cannot work, but it also does not display an error
